### ISSUE TITLE
Overwrite __init___ and others?

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#11]
In issue #9 @ilevkivskyi suggests that we should raise an error if any class attribute we're trying to set is already used. This includes `__init__`, `__eq__`, etc. He notes that the typing module raises AttributeError in these cases.

Note that the caller can suppress the generation of `__eq__` by setting `cmp=False`, can suppress `__repr__` by setting `repr=False`, can suppress the generation of `__init__` by setting `init=False`, etc.

I think raising an AttributeError if we try to overwrite a dunder method is a good idea. The caller has the choice to either write their own method and suppress ours, or use ours. But the can't try to do both.

Edit: Fix `init=False` instead of `__init__=False`.

**Comment by gvanrossum** [comment]
Sgtm, but why not init=False?

**Comment by ericvsmith** [comment]
Typo. Should be `init=False`.

**Comment by Dutcho** [comment]
After fixing on Jun 4, this issue seems to be unfixed in the replacement of `_set_attribute()` by `_set_new_attribute()`. The latter's result (`True` if attribute already exists) is silently ignored for `__init__`, `__repr__`, and `__eq__` (but not for other comparators like `__lt__` and attribute accessors like `__setattr__`, which still raise "`cannot overwrite`" exceptions).
Don't know whether this was on purpose, but if so it may need documenting to prevent surprised users.
