### ISSUE TITLE
dataclasses are not cooperative

### ISSUE THREAD

**Issue by a-recknagel** [ericvsmith/dataclasses#142]
dataclasses are not cooperative:
```python
>>> class SayFoo:
...     def __init__(self, *args, **kwargs):
...         print('Foo')
...         super().__init__(*args, **kwargs)
... 
>>> @dataclass
... class DC(SayFoo):
...     var: int
...     
>>> DC(1)
DC(var=1)  # doesn't say 'Foo'
```
This makes writing useful mixins for dataclasses quite hard. Is there a reason why they were written this way?

**Comment by ericvsmith** [comment]
Because I don't know the signature of the base class's `__init__`. You may call it yourself in `__post_init__`.

I'm closing this because this repo is only for the backport of dataclasses to Python 3.6. If you want to discuss this further, I recommend using the python-dev mailing list, or bugs.python.org.

**Comment by a-recknagel** [comment]
Thanks for the answer, sorry for using the wrong channel.
