### ISSUE TITLE
Change the names of the class-level "eq" and "compare" parameters?

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#90]
"compare" makes no sense: it's about ordering. It should be changed to "order".

What about "eq"? It's sort of cryptic. Should it be "compare"? Or is that confusing with the historical use of "cmp"?

**Comment by ilevkivskyi** [comment]
I think ``eq`` is OK. ``__eq__`` is often used for custom classes, in my experience it was one of the first dunders I ever used (although maybe my scientific background caused some bias).

**Comment by ericvsmith** [comment]
In #1, @ncoghlan suggested `orderable` (for the current `compare`) and `hashable` (for `hash`). I don't see a suggestion for what's currently `eq`. I think `frozen`, `repr`, and `init` are fine as-is, and `eq` probably falls in the same category.

So maybe the best thing is just change `compare` to `order` and nothing else. I think `hash` for "generate a hash function" is okay.

**Comment by ilevkivskyi** [comment]
> So maybe the best thing is just change ``compare`` to ``order`` and nothing else. I think ``hash`` for "generate a hash function" is okay.

+1

**Comment by gvanrossum** [comment]
+1 to changing compare->order only. Several of the others are dunder names without the dunders (init, repr, eq, hash).

**Comment by chadrik** [comment]
For the record, I don't love `order` because it's a verb.  A user is not telling the API to *order* their class, they are declaring that their class is intrinsically *ordered*.  I prefer adjectives where the args don't match dunder names.

**Comment by ncoghlan** [comment]
I agree with the idea of "protocol method name without the prefix & suffix" being a good baseline convention. That way it's only the ordered comparison parameter name that's up for discussion.

By the baseline convention, since these parameter names are also method names, it's actually OK for them to be verbs. And if we ever decided it made sense to bring back support for cmp-style ordering implementations (perhaps as an alternative input format for `functools.total_ordering`), then `def __order__(self, other):` would be a reasonable name for that.
