### ISSUE TITLE
Better default for List, Set, Dict?

### ISSUE THREAD

**Issue by JimJJewett** [ericvsmith/dataclasses#93]
Given that List, Set, and Dict are markers from typing, rather than real classes, would it be reasonable to automatically fill in the default call to field?

e.g., should the Dict of

    constraints: Dict[str, str]

without a default value imply

    constraints: Dict[str, str] = field(default_factory=dict)

**Comment by ericvsmith** [comment]
I don't want to ever provide a default or default factory. It's up to the class designer to do that. If I automatically add a default value, then that parameter would not need to be passed to `__init__`, which is something the class designer, not dataclasses, needs to define.

**Comment by ericvsmith** [comment]
Although I guess you could say that:
```
   constraints: Dict[str, str] = Dict
```
Could set `dict` as the `default_factory`. That is, key it off of the default value rather than the type. I'd like to keep with dataclasses ignoring the annotation, except for `ClassVar` and `InitVar`.

That said, I'm not convinced it's a good idea. I'm also not sure what it would mean for mypy.

**Comment by gvanrossum** [comment]
Ouchie. `= Dict` makes no sense -- static checkers will interpret it as a
default value that's a type rather than an instance of that type.

**Comment by ericvsmith** [comment]
My point was: it absolutely should not be driven from the type annotation, and if anything should be driven by a sentinel object as the default. I chose a bad sentinel as an example!

I'm going to close this. At least in the first version, I don't want to add any more special behaviors.
